/**
 * COLOR-SAFE System Constants and Controlled Scientific Vocabulary
 */

const ROLES = {
  OFFICER: 'OFFICER',
  ADMIN: 'ADMIN',
};

const TEST_STATUS = {
  DRAFT: 'DRAFT',
  IN_PROGRESS: 'IN_PROGRESS',
  ANALYSING: 'ANALYSING',
  COMPLETED: 'COMPLETED',
  INCONCLUSIVE: 'INCONCLUSIVE',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  SYNCED: 'SYNCED',
};

const CAPTURE_STATUS = {
  CAPTURED: 'CAPTURED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
};

const CLASSIFICATION_RESULT = {
  PRESUMPTIVE_POSITIVE: 'PRESUMPTIVE_POSITIVE',
  PRESUMPTIVE_NEGATIVE: 'PRESUMPTIVE_NEGATIVE',
  INCONCLUSIVE: 'INCONCLUSIVE',
};

const AUDIT_ACTIONS = {
  TEST_CREATED: 'TEST_CREATED',
  CAPTURE_STARTED: 'CAPTURE_STARTED',
  CAPTURE_FAILED: 'CAPTURE_FAILED',
  CAPTURE_COMPLETED: 'CAPTURE_COMPLETED',
  ANALYSIS_STARTED: 'ANALYSIS_STARTED',
  ANALYSIS_COMPLETED: 'ANALYSIS_COMPLETED',
  RESULT_GENERATED: 'RESULT_GENERATED',
  RECORD_CREATED: 'RECORD_CREATED',
  RECORD_SIGNED: 'RECORD_SIGNED',
  REPORT_GENERATED: 'REPORT_GENERATED',
  RECORD_VERIFIED: 'RECORD_VERIFIED',
  SYNCED: 'SYNCED',
};

const MANDATORY_DISCLAIMERS = {
  PRESUMPTIVE_HEADER: 'PRESUMPTIVE FIELD-TEST RECORD',
  LAB_CONFIRMATION_REQUIRED: 'LABORATORY CONFIRMATION REQUIRED',
  LIMITATION_STATEMENT: 'This report represents a presumptive field-test interpretation and does not replace laboratory confirmation. Results must be validated by an accredited forensic laboratory.',
};

module.exports = {
  ROLES,
  TEST_STATUS,
  CAPTURE_STATUS,
  CLASSIFICATION_RESULT,
  AUDIT_ACTIONS,
  MANDATORY_DISCLAIMERS,
};
